### ISSUE TITLE
공통 - 뱃지 컴포넌트 구현 

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#11]
# 📌간단한 기능 설명
공통 컴포넌트인 `뱃지` 컴포넌트를 제작합니다.
# 📄Todo
- [x] `width`, `height`, `children` props 받기
- [x] 자주 사용되는 사이즈 정의
- [x] hover, isActive 추가
- [x] 자주 사용되는 색깔 정의(배경색, 글자색)
<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
