### ISSUE TITLE
SharedBundleBox 컴포넌트 구현

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#124]
# 📌간단한 기능 설명
SharedBundleBox를 구현합니다.
# 📄Todo
- [ ] 전체 선택 가능 
- [ ] 선택한 요소만 추가 가능
- [ ] 드롭다운 컴포넌트 이용하기
- [ ] 질문 개수 표기
<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
