### ISSUE TITLE
공통 - 아이콘 래핑 구현

### ISSUE THREAD

**Issue by SoJuSo** [Team-kiwing/Team-3seco-kiwing-fe#13]
# 📌간단한 기능 설명
아이콘 래핑 기능을 구현합니다.

# 📄Todo
- [x] props 형태, 타입 지정하기
- [x] default value 할당하기
- [x] 실제 사용형태 확인
- [x] 사각? 원형을 고려해야하는지 여부 << 일단 구현 후 생각

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
