### ISSUE TITLE
공통 - DropDown 구조 변경

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#135]
# 📌간단한 기능 설명
기존 DropDown이 모바일에서 제대로 동작하지 않는 이슈가 발생했습니다.
원인은 내부 구조의 불필요한 속성들 때문에 viewport 밖으로 나간것으로 보입니다.
따라서 DropDown 내부 구조를 변경하여 버그를 픽스합니다.
또한 DropDown이 뜨는 위치를 커스텀 할 수 없었기 때문에 direction을 정할 수 있도록 기능을 추가합니다.

# 📄Todo
- [ ] DropDown 내부 불필요한 속성 제거
- [ ] DropDown direction props 추가
- [ ] useDropDown hook 추가

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
