### ISSUE TITLE
공통 - Input 컴포넌트 border 옵션 추가

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#152]
# 📌간단한 기능 설명

Input 컴포넌트를 사용할 때 border 옵션을 선택할 수 있도록 props를 추가합니다.

# 📄Todo

- [x] Input props 확장 (border를 bottom만 할 것인지, 4방면 다 할 것인지)
- [x] props에 맞는 스타일링
- [x] 전역 스타일 수정

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
