### ISSUE TITLE
공통 - Badge 컴포넌트 디자인 수정

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#163]
# 📌간단한 기능 설명
뱃지 컴포넌트 디자인을 수정합니다.
# 📄Todo
- [ ] 스크랩 뱃지 스타일 배경색 수정
- [x] HOT 뱃지 스타일에서 `text` 가운데 정렬하기
- [x] Basic 스타일 배경색 수정(잘안보이는 이슈)

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
