### ISSUE TITLE
SharedBundleDropDown 컴포넌트 버전업

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#209]
# 📌간단한 기능 설명
바뀐 DropDown컴포넌트를 이용하여 버전업을 합니다.
# 📄Todo
- [x] 바뀐 DropDown 적용하기
- [x] bundle 아이디 값 받아오는 props 추가
- [x] 꾸러미에 추가하는 함수 props 추가

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
