### ISSUE TITLE
페이지 - MainPage 리펙토링

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#253]
# 📌간단한 기능 설명

MainPage에서 쓰이는 컴포넌트 수정사항을 반영합니다.

# 📄Todo

- [x] UserInfoCard 오른쪽 버튼 출력
- [ ] 사용자 id 출력 시 앞에 @ 빼고 출력하기
- [ ] 배너 이미지 추가하기

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
