### ISSUE TITLE
페이지 - 꾸러미, 꾸러미 상세 페이지 레이아웃 수정

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#266]
# 📌간단한 기능 설명
꾸러미와 꾸러미 상세 페이지의 레이아웃을 수정합니다.
# 📄Todo
- [x] max-width 1200px 로 지정하기
- [x] 웹 환경 `padding-top`: 3rem, 모바일 환경 `padding-top`: 2rem 지정하기
- [x] 웹 환경 `width`: 80%, 모바일 환경 `width`: 90% 지정하기

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
