### ISSUE TITLE
공통 - UserInfoCard 로그아웃 기능 리팩토링

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#278]
# 📌간단한 기능 설명

UserInfoCard 컴포넌트에서 로그아웃 기능을 수정합니다.

# 📄Todo

- [ ] 로그아웃 컨펌창 띄우기
- [ ] 로그아웃 시 `auth/logout` api 호출
- [ ] api 호출 뒤 userStore 초기화
- [ ] 모달에서 회원정보 수정 후 새로고침 대신 refetchQuery 사용하기

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
