### ISSUE TITLE
로그인, 회원가입 오류 수정

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#280]
# 📌간단한 기능 설명

로그인, 회원가입 과정에서 생긴 오류를 수정합니다.

# 📝TODO

- [ ] 링크 입력할 때 정규 표현식으로 이상한 링크 걸러내기 (UserInfoCard에서도 적용하기)
- [ ] Register, Auth 페이지로 리다이렉트 될 때 메인페이지가 잠깐 보이는 것 수정
- [ ] 로그인 한 뒤 정보 입력을 안하고 메인으로 갔을때 메인이 잠깐 보임 => 이는 레지스터 페이지에서 탑, 바텀 네브바를 없앰으로써 해결
- [x] 로그인 안 했을 때 레지스터 페이지로 가지는 버그 수정

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
