### ISSUE TITLE
공통 - Input 컴포넌트 구현

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#29]
# 📌간단한 기능 설명

공통 컴포넌트인 Input 컴포넌트를 구현합니다.

# 📄Todo

- [x] input 레이아웃 잡기
- [x] border-bottom만 설정
- [x] 라벨 기입 가능하게
- [x] 에러 메시지는 input 아래 왼쪽 정렬

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
