### ISSUE TITLE
페이지 - MainPage 디자인 피드백 반영

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#338]
# 📌간단한 기능 설명

MainPage 디자인 피드백을 반영합니다.

# 📄Todo

- [x] UserInfoCard 사용자 ID 앞에 @ 붙이기
- [x] 최근 등록된 질문, 최근 등록된 꾸러미 굵기를 500으로 수정하기
- [x] 최근 등롣된 질문과 최근 등록된 꾸러미 사이 중간선 길이 조정하기

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
