### ISSUE TITLE
페이지 - MyBundlePage QA

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#347]
# 📌간단한 기능 설명
내 꾸러미 페이지에서 QA 진행 후 디자인을 개선합니다.
# 📄Todo
- [ ] MybundleItem font-weight: 400으로 변경
- [ ] QuestionBox font-weight: 300으로 변경
- [ ] 모바일에서 MyBundleItem 사이 gap 줄이기
- [ ] 그랩 아이콘 바깥으로 분리
- [ ] 질문/꾸러미 추가하면 맨 아래로 스크롤 내려가도록 만들기

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
