### ISSUE TITLE
페이지 - 내 꾸러미 페이지 UI 개선

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#378]
# 📌간단한 기능 설명
내 꾸러미 페이지의 UI를 개선합니다.

# 📄Todo
- [ ] 모바일 환경에서의 여백 조정
- [ ] 내가 작성한 질문 클릭 시 목차 컴포넌트도 따라가도록 변경
- [ ] 내가 작성한 질문 클릭 시 비어있는 경우 UI 추가

> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
