### ISSUE TITLE
공통 - Button(Rectangle) 컴포넌트 구현

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#38]
# 📌간단한 기능 설명
사각형 버튼을 구현합니다.

# 📄Todo
- [ ] 사각형 버튼 레이아웃 틀 잡기
- [ ] width, height 등 커스텀 옵션 제공
- [ ] 상호작용 css 적용

> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
