### ISSUE TITLE
공통 - DropDown 컴포넌트 구현

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#40]
# 📌간단한 기능 설명
드롭다운 컴포넌트를 구현합니다.

# 📄Todo
- [ ] 드롭다운 레이아웃 틀 잡기
- [ ] 일정 길이 이상 height가 늘어나면 스크롤 제공
- [ ] 각 아이템 선택 시 동작할 handler 함수 연동

> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
