### ISSUE TITLE
공통 - 모달

### ISSUE THREAD

**Issue by SoJuSo** [Team-kiwing/Team-3seco-kiwing-fe#42]
# 📌간단한 기능 설명
#### 모달의 경우 고민해봐도 어쩔 수 없이 태스크가 커질 것 같습니다. 양해부탁드립니다.

프로젝트 전역에서 사용되는 모달을 구현합니다.

# 📄Todo
- [ ] 전역 모달 구현합니다.
- [ ] 모달은 변수, 함수를 전달받을 수 있습니다.
- [ ] 모달은 뒤 배경을 무시합니다.
- [ ] 모달은 기본값으로 상단 우측에 X 버튼이 존재하고, 모달 외곽을 클릭하면 모달이 닫힙니다.

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
