### ISSUE TITLE
공통 - 내비게이션 바 통합 리팩토링

### ISSUE THREAD

**Issue by SoJuSo** [Team-kiwing/Team-3seco-kiwing-fe#43]
# 📌간단한 기능 설명
분리구현된 내비게이션 바를 하나의 통합적인 브랜치에서 통합, 관리합니다.

# 📄Todo
- [ ] - 상수를 전역에서 사용되는 형태로 변경합니다.
- [ ] - 색상을 전역 테마에서 가져오는 형태로 변경합니다.
- [ ] - 테마 변경에 따른 색상 변경값을 지원하도록 합니다.

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
