### ISSUE TITLE
공통 - 아바타 컴포넌트 제작

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#5]
# 📌간단한 기능 설명

공통 컴포넌트인 `아바타` 컴포넌트를 구현합니다.

# 📄Todo

- [x] 아바타 컴포넌트 틀 잡기
- [x] 유저 카드에서의 아바타 사이즈 지정
- [x] NavBar에서의 아바타 사이즈 지정
- [x] 웹 / 모바일 사이즈 고려

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
