### ISSUE TITLE
공통 - 뱃지 컴포넌트 리펙토링

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#52]
# 📌간단한 기능 설명
공통 컴포넌트인 뱃지 컴포넌트 리펙토링합니다.
# 📄Todo
- [x] xs, xss 사이즈 추가
- [x] margin 값 받는 props 추가
- [x] hot 뱃지 디자인 추가
<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
