### ISSUE TITLE
공통 - Selector 컴포넌트 구현

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#55]
# 📌간단한 기능 설명
공통 컴포넌트인 Selector 컴포넌트를 구현합니다.
# 📄Todo
- [x] 글자 크기(size)를 받습니다.
- [x] 요소가 될 text를 받습니다.
- [x] 클릭 된것을 넘겨줍니다.
<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
