### ISSUE TITLE
공통 - BundleCard 컴포넌트 구현

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#64]
# 📌간단한 기능 설명
질문꾸러미 card를 구현합니다.
# 📄Todo
- [x] 피그마 토대로 스타일링
- [x] 클릭시 해당 페이지 이동
- [x] msw 이용하여 구현

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
