### ISSUE TITLE
공통 - UserInfoCard 컴포넌트 리펙토링

### ISSUE THREAD

**Issue by JaeHyunGround** [Team-kiwing/Team-3seco-kiwing-fe#65]
# 📌간단한 기능 설명

공통 컴포넌트인 `UserInfoCard` 컴포넌트의 기능들을 구현합니다.

# 📄Todo

- [x] 정보 수정, 로그아웃 버튼 클릭 시 각각 `모달이 뜨도록`, `confirm 창 띄운 후 로그아웃 되게` 구현하기
- [x] API 명세서가 나오는대로 데이터 형식에 맞춰서 props 수정하기
- [x] 인포카드 전체 너비 100%로 수정
- [x] 오른쪽 버튼 출력 유무 컨트롤 props 추가

<br />
> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
