### ISSUE TITLE
공통 - 섀도잉 박스 구현

### ISSUE THREAD

**Issue by kim-hyunjoo** [Team-kiwing/Team-3seco-kiwing-fe#8]
# 📌간단한 기능 설명
아이템을 담는 박스 레이아웃인 `섀도잉 박스` 를 구현합니다.
# 📄Todo
- [ ] 섀도잉 박스 틀 잡기
- [ ] `width`, `height`, `children` props 열여주기
- [ ] `border-radius` 6~10px 사이로 부여하기
- [ ] 웹/모바일 환경 고려하기

> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
