### ISSUE TITLE
공통 - 스켈레톤 컴포넌트 구현

### ISSUE THREAD

**Issue by pkb9239** [Team-kiwing/Team-3seco-kiwing-fe#9]
# 📌간단한 기능 설명
공통 컴포넌트인 `스켈레톤` 컴포넌트를 제작합니다.

# 📄Todo 
- [x] 스켈레톤 컴포넌트 기본 Base 구현
- [x] Circle 형태의 스켈레톤 구현
- [x] Box 형태의 스켈레톤 구현
- [x] Paragraph 형태의 스켈레톤 구현
- [x] 다양한 props 열여주기
- [ ] 웹/모바일 환경 고려하기
<br />

> 브랜치 명시 규칙
${issue번호}/${컴포넌트 명시}-${버전 명시}
ex) #123/signUpPage-3.1.0
